services:
  - type: web
    name: site-osint-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: HOTMART_HOTTOK
        sync: false
      - key: HOTMART_CHECKOUT_URL
        sync: false
      - key: MAKE_WEBHOOK_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: REPORT_FROM
        sync: false
      - key: MP_ACCESS_TOKEN
        sync: false
